spring.application.name=cinebook

# Spring Boot server
server.port=8080

# MongoDB Atlas
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=test

# Frontend
app.client-url=http://localhost:5173
logging.level.org.springframework.security=INFO
spring.thymeleaf.cache=false